import type { BlogsResponse, BlogResponse, CreateBlogInput } from '@/types/blog';

const API_BASE_URL = 'http://localhost:3001';

// Fetch all blogs from JSON Server
// Returns array of blog objects that I then map over in BlogSidebar
export async function fetchBlogs(): Promise<BlogsResponse> {
  try {
    const response = await fetch(`${API_BASE_URL}/blogs`);
    
    if (!response.ok) {
      throw new Error(`Failed to fetch blogs: ${response.statusText}`);
    }
    
    const data: BlogsResponse = await response.json();
    return data;
  } catch (error) {
    // I'm checking if it's an Error instance before accessing .message
    // to avoid TypeScript unknown type issues
    if (error instanceof Error) {
      throw new Error(`Error fetching blogs: ${error.message}`);
    }
    throw new Error('An unknown error occurred while fetching blogs');
  }
}

// Get single blog by ID - used in BlogDetail component
export async function fetchBlogById(id: number): Promise<BlogResponse> {
  try {
    const response = await fetch(`${API_BASE_URL}/blogs/${id}`);
    
    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Blog not found');
      }
      throw new Error(`Failed to fetch blog: ${response.statusText}`);
    }
    
    const data: BlogResponse = await response.json();
    return data;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Error fetching blog: ${error.message}`);
    }
    throw new Error('An unknown error occurred while fetching the blog');
  }
}

/**
 * Create a new blog
 * @param blogData - Blog data without id (id is auto-generated by JSON Server)
 * @returns Promise<BlogResponse> - Created blog object with generated id
 */
export async function createBlog(blogData: CreateBlogInput): Promise<BlogResponse> {
  try {
    // Add current date if not provided
    const blogWithDate = {
      ...blogData,
      date: new Date().toISOString(),
    };

    const response = await fetch(`${API_BASE_URL}/blogs`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(blogWithDate),
    });
    
    if (!response.ok) {
      throw new Error(`Failed to create blog: ${response.statusText}`);
    }
    
    const data: BlogResponse = await response.json();
    return data;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Error creating blog: ${error.message}`);
    }
    throw new Error('An unknown error occurred while creating the blog');
  }
}
